<?php
session_start();
include "db.php";
require_once __DIR__ . "/fpdf.php";

if (!isset($_SESSION['user_id'])) {
    die("Please login first.");
}

$user_id = (int)$_SESSION['user_id'];
$id  = (int)($_GET['id'] ?? 0);
$src = strtolower(trim($_GET['src'] ?? 'core'));

if ($id <= 0) {
    die("Invalid transaction.");
}

if ($src === 'vtu') {
    $stmt = $conn->prepare("
        SELECT id, user_id, service, provider, ref, network, phone, plan_id,
               amount_sell, amount_cost, profit, status, provider_message, created_at
        FROM vtu_transactions
        WHERE id = ? AND user_id = ?
        LIMIT 1
    ");
    $stmt->bind_param("ii", $id, $user_id);
    $stmt->execute();
    $tx = $stmt->get_result()->fetch_assoc();
    $stmt->close();

    if (!$tx) die("Transaction not found");
} else {
    $stmt = $conn->prepare("
        SELECT id, user_id, type, service, amount, status, reference, description, created_at
        FROM transactions
        WHERE id = ? AND user_id = ?
        LIMIT 1
    ");
    $stmt->bind_param("ii", $id, $user_id);
    $stmt->execute();
    $tx = $stmt->get_result()->fetch_assoc();
    $stmt->close();

    if (!$tx) die("Transaction not found");
}

$userStmt = $conn->prepare("SELECT fullname, email, phone FROM users WHERE id=? LIMIT 1");
$userStmt->bind_param("i", $user_id);
$userStmt->execute();
$user = $userStmt->get_result()->fetch_assoc();
$userStmt->close();

class ReceiptPDF extends FPDF
{
    function Header()
    {
        $logo = __DIR__ . '/assets/logo.png';
        if (file_exists($logo)) {
            $this->Image($logo, 15, 10, 28);
        }

        $this->SetFont('Arial', 'B', 18);
        $this->Cell(0, 10, 'VTUTOPUP RECEIPT', 0, 1, 'R');
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 6, 'Transaction Receipt', 0, 1, 'R');
        $this->Ln(8);
        $this->Line(15, 35, 195, 35);
        $this->Ln(8);
    }

    function Footer()
    {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 9);
        $this->Cell(0, 10, 'Generated by VTUTOPUP', 0, 0, 'C');
    }

    function RowItem($label, $value)
    {
        $this->SetFont('Arial', 'B', 11);
        $this->Cell(55, 10, $label, 0, 0);
        $this->SetFont('Arial', '', 11);
        $this->MultiCell(120, 10, $value, 0);
    }
}

$pdf = new ReceiptPDF();
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 20);

$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, 'Customer Details', 0, 1);
$pdf->Ln(2);
$pdf->RowItem('Full Name:', (string)($user['fullname'] ?? ''));
$pdf->RowItem('Email:', (string)($user['email'] ?? ''));
$pdf->RowItem('Phone:', (string)($user['phone'] ?? ''));
$pdf->Ln(4);

$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, 'Transaction Details', 0, 1);
$pdf->Ln(2);

if ($src === 'vtu') {
    $pdf->RowItem('Reference:', (string)($tx['ref'] ?? ''));
    $pdf->RowItem('Service:', (string)($tx['service'] ?? ''));
    $pdf->RowItem('Provider:', (string)($tx['provider'] ?? ''));
    $pdf->RowItem('Network:', (string)($tx['network'] ?? ''));
    $pdf->RowItem('Phone / Meter:', (string)($tx['phone'] ?? ''));
    $pdf->RowItem('Amount:', 'NGN ' . number_format((float)($tx['amount_sell'] ?? 0), 2));
    $pdf->RowItem('Cost:', 'NGN ' . number_format((float)($tx['amount_cost'] ?? 0), 2));
    $pdf->RowItem('Profit:', 'NGN ' . number_format((float)($tx['profit'] ?? 0), 2));
    $pdf->RowItem('Status:', ucfirst((string)($tx['status'] ?? 'pending')));
    $pdf->RowItem('Message:', (string)($tx['provider_message'] ?? ''));
    $pdf->RowItem('Date:', (string)($tx['created_at'] ?? ''));
    $refName = (string)($tx['ref'] ?? 'receipt');
} else {
    $pdf->RowItem('Reference:', (string)($tx['reference'] ?? ''));
    $pdf->RowItem('Service:', (string)($tx['service'] ?? ''));
    $pdf->RowItem('Type:', ucfirst((string)($tx['type'] ?? '')));
    $pdf->RowItem('Amount:', 'NGN ' . number_format((float)($tx['amount'] ?? 0), 2));
    $pdf->RowItem('Status:', ucfirst((string)($tx['status'] ?? 'pending')));
    $pdf->RowItem('Description:', (string)($tx['description'] ?? ''));
    $pdf->RowItem('Date:', (string)($tx['created_at'] ?? ''));
    $refName = (string)($tx['reference'] ?? 'receipt');
}

$filename = 'receipt_' . preg_replace('/[^A-Za-z0-9_\-]/', '_', $refName) . '.pdf';
$pdf->Output('D', $filename);
exit;
